// import { useTranslation } from './hooks/useTranslation'; // Replace 'your-translation-library' with the actual library you're using

// export const ErrorHandfler = () => {
//   const { translate } = useTranslation();

//   const ErrorMessges =(substatusCode: string) =>{
//     switch (substatusCode) {
//         case "invalid.phone":
//           return translate.t("ERROR_INVALID_PHONE");
//         case "invalid.DOB":
//           return translate.t("ERROR_INVALID_DOB");
//         case "category.not.found":
//           return translate.t("ERROR_CATEGORY_NOT_FOUND");
//         case "bike.not.found":
//           return translate.t("ERROR_BIKE_NOT_FOUND");
//         case "post.not.found":
//           return translate.t("ERROR_POST_NOT_FOUND");
//         case "comment.not.found":
//           return translate.t("ERROR_COMMENT_NOT_FOUND");
//         case "touring.not.found":
//           return translate.t("ERROR_TOURING_NOT_FOUND");
//         case "bol.not.foud":
//           return translate.t("ERROR_BOL_NOT_FOUND");
//         case "blog.comment.not.found":
//           return translate.t("ERROR_BLOG_COMMENT_NOT_FOUND");
//         case "thred.comment.not.found":
//           return translate.t("ERROR_THREAD_COMMENT_NOT_FOUND");
//         case "token.expire.or.invalid":
//           return translate.t("ERROR_TOKEN_EXPIRE_OR_INVALID");
//         case "token.Invalid":
//           return translate.t("ERROR_TOKEN_INVALID");
//         case "blogId.Invalid":
//           return translate.t("ERROR_BLOG_ID_INVALID");
//         case "blog.comment.id.Invalid":
//           return translate.t("ERROR_BLOG_COMMENT_ID_INVALID");
//         case "email.Invalid":
//           return translate.t("ERROR_EMAIL_INVALID");
//         case "email.not.found":
//           return translate.t("ERROR_EMAIL_NOT_FOUND");
//         case "password.wrong":
//           return translate.t("ERROR_PASSWORD_WRONG");
//         case "emai.not.exist":
//           return translate.t("ERROR_EMAIL_NOT_EXIST");
//         case "emai.already.exist":
//           return translate.t("ERROR_EMAIL_ALREADY_EXIST");
//         case "oldPassword.Invalid":
//           return translate.t("ERROR_OLD_PASSWORD_INVALID");
//         case "password.Invalid":
//           return translate.t("ERROR_PASSWORD_INVALID");
//         case "password.old.wrong":
//           return translate.t("ERROR_PASSWORD_OLD_WRONG");
//         case "newPassword.Invalid":
//           return translate.t("ERROR_NEW_PASSWORD_INVALID");
//         case "nickName.Invalid":
//           return translate.t("ERROR_NICKNAME_INVALID");
//         case "gender.Invalid":
//           return translate.t("ERROR_GENDER_INVALID");
//         case "invalid.DOB":
//           return translate.t("ERROR_INVALID_DOB");
//         case "province.Invalid":
//           return translate.t("ERROR_PROVINCE_INVALID");
//         case "birth.Invalid":
//           return translate.t("ERROR_BIRTH_INVALID");
//         case "password.Invalid":
//           return translate.t("ERROR_PASSWORD_INVALID");
//         case "comment.Invalid":
//           return translate.t("ERROR_COMMENT_INVALID");
//         case "blog.title.Invalid":
//           return translate.t("ERROR_BLOG_TITLE_INVALID");
//         case "blog.bikeId.Invalid":
//           return translate.t("ERROR_BLOG_BIKE_ID_INVALID");
//         case "blog.categoryId.Invalid":
//           return translate.t("ERROR_BLOG_CATEGORY_ID_INVALID");
//         case "blog.body.Invalid":
//           return translate.t("ERROR_BLOG_BODY_INVALID");
//         case "blog.shareWith.Invalid":
//           return translate.t("ERROR_BLOG_SHARE_WITH_INVALID");
//         case "blog.thumbnail.Invalid":
//           return translate.t("ERROR_BLOG_THUMBNAIL_INVALID");
//         case "touring.destination.Invalid":
//           return translate.t("ERROR_TOURING_DESTINATION_INVALID");
//         case "touring.budgetMin.Invalid":
//           return translate.t("ERROR_TOURING_BUDGET_MIN_INVALID");
//         case "touring.budgetMax.Invalid":
//           return translate.t("ERROR_TOURING_BUDGET_MAX_INVALID");
//         case "touring.numberOfMembers.Invalid":
//           return translate.t("ERROR_TOURING_NUMBER_OF_MEMBERS_INVALID");
//         case "touring.roomName.Invalid":
//           return translate.t("ERROR_TOURING_ROOM_NAME_INVALID");
//         case "touring.title.Invalid":
//           return translate.t("ERROR_TOURING_TITLE_INVALID");
//         case "touring.body.Invalid":
//           return translate.t("ERROR_TOURING_BODY_INVALID");
//         case "touring.status.Invalid":
//           return translate.t("ERROR_TOURING_STATUS_INVALID");
//         case "posts.categoryId.Invalid":
//           return translate.t("ERROR_POSTS_CATEGORY_ID_INVALID");
//         case "posts.bikeId.Invalid":
//           return translate.t("ERROR_POSTS_BIKE_ID_INVALID");
//         case "posts.location.Invalid":
//           return translate.t("ERROR_POSTS_LOCATION_INVALID");
//         case "posts.body.Invalid":
//           return translate.t("ERROR_POSTS_BODY_INVALID");
//         case "posts.shareWith.Invalid":
//           return translate.t("ERROR_POSTS_SHARE_WITH_INVALID");
//         case "posts.status.Invalid":
//           return translate.t("ERROR_POSTS_STATUS_INVALID");
//         case "blogs.body.Invalid":
//           return translate.t("ERROR_BLOGS_BODY_INVALID");
//         case "blogs.categoryId.Invalid":
//           return translate.t("ERROR_BLOGS_CATEGORY_ID_INVALID");
//         case "blogs.location.Invalid":
//           return translate.t("ERROR_BLOGS_LOCATION_INVALID");
//         case "blogs.shareWith.Invalid":
//           return translate.t("ERROR_BLOGS_SHARE_WITH_INVALID");
//         case "blogs.postId.Invalid":
//           return translate.t("ERROR_BLOGS_POST_ID_INVALID");
//         case "blogs.comment.Invalid":
//           return translate.t("ERROR_BLOGS_COMMENT_INVALID");
//         case "blogs.parentId.Invalid":
//           return translate.t("ERROR_BLOGS_PARENT_ID_INVALID");
//         case "blogs.postCommentId.Invalid":
//           return translate.t("ERROR_BLOGS_POST_COMMENT_ID_INVALID");
//         case "blog.not.found":
//           return translate.t("ERROR_BLOG_NOT_FOUND");
//         case "blogs.comment.not.found":
//           return translate.t("ERROR_BLOGS_COMMENT_NOT_FOUND");
//         case "thread.name.Invalid":
//           return translate.t("ERROR_THREADS_NAME_INVALID");
//         case "thread.categoryId.Invalid":
//           return translate.t("ERROR_THREADS_CATEGORY_ID_INVALID");
//         case "thread.threadName.Invalid":
//           return translate.t("ERROR_THREADS_THREAD_NAME_INVALID");
//         case "thread.comment.Invalid":
//           return translate.t("ERROR_THREADS_COMMENT_INVALID");
//         case "touring.destination.Invalid":
//           return translate.t("ERROR_TOURING_DESTINATION_INVALID");
//         case "touring.numberOfMembers.Invalid":
//           return translate.t("ERROR_TOURING_NUMBER_OF_MEMBERS_INVALID");
//         case "touring.roomName.Invalid":
//           return translate.t("ERROR_TOURING_ROOM_NAME_INVALID");
//         case "touring.title.Invalid":
//           return translate.t("ERROR_TOURING_TITLE_INVALID");
//         case "touring.body.Invalid":
//           return translate.t("ERROR_TOURING_BODY_INVALID");
//         case "touring.status.Invalid":
//           return translate.t("ERROR_TOURING_STATUS_INVALID");
//         case "touring.touringId.Invalid":
//           return translate.t("ERROR_TOURING_TOURING_ID_INVALID");
//         case "touring.not.found":
//           return translate.t("ERROR_TOURING_NOT_FOUND");
//         case "expire.Token":
//           return translate.t("ERROR_EXPIRED_TOKEN");
//         case "expire.forgot.link":
//           return translate.t("ERROR_EXPIRED_FORGOT_LINK");
//         case "user.not.found":
//           return translate.t("ERROR_USER_NOT_FOUND");
//         case "bike.not.founr":
//           return translate.t("ERROR_BIKE_NOT_FOUND");
//         case "comment.not.found":
//           return translate.t("ERROR_COMMENT_NOT_FOUND");
//         case "thread.comment.not.found":
//           return translate.t("ERROR_THREAD_COMMENT_NOT_FOUND");
//         case "categor.not.found":
//           return translate.t("ERROR_CATEGORY_NOT_FOUND");
//         case "thread.user.not.found":
//           return translate.t("ERROR_THREAD_USER_NOT_FOUND");
//         case "thread.not.found":
//           return translate.t("ERROR_THREAD_NOT_FOUND");
//         case "unknow.user":
//           return translate.t("ERROR_UNKNOWN_USER");
//         default:
//           return translate.t("ERROR_DEFAULT"); // Provide a default error message if no specific case matches
//       }
//   }
  
// };
